In [1]:
# E1 

import numpy as np

arr = np.array([range(0,10)]) # Here using range(x,y) lists numbers that comprises of values in range x to y with x included and y excluded and np.array makes an array of these values
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [2]:
# E2
arr_1 = arr % 2==1 # this condition creates a list with boolean values, i.e. , True or False depending on the condition and values

arr_filter = arr[arr_1] # this statement creates the array,arr_filter, with those elements where the condition in previous statement is True
# for eg, let say at 1, the condition holds True while at 0, it holds false. So 1 will be included in arr_filtered while 0 won't.

arr_filter

array([1, 3, 5, 7, 9])

In [3]:
# E3
arr_2 = np.where(arr%2!=0, -1, arr)
# where() function is used to replace the values in an array.
# np.where(condition, new value, array): Condition is checked in the array. New value is the value that will be entered everywhere the condition holds true. Array is that array where changes are to be made.
arr_2

array([[ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]])

In [4]:
# E4
arr=np.arange(10)
arr = np.reshape(arr,(2,5)) # reshape(array, (rows,columns))
# the product of new number of rows and columns shuld be equal to the product of original number of rows and columns
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# E5
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b) # intersect1d(array1, array2) gives the common values of two arrays.
c

array([2, 4])

In [6]:
# E6
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>4)&(a<11)] # checks the condition and gives all values between 4 and 11, both excluded.

array([ 6,  9, 10])

In [7]:
# E7
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
            [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a_sum = a.sum() # Adds all the elements
a_max = a.max() # Gives the maximum value in the array
print (a_sum)
print (a_max)

4.8595784
0.82485143


In [8]:
# E8
x = np.array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],[5.4627315, 0.5093587, 4.0067661, 5.5645993],[1.2697628, 8.2485143, 2.6590556, 5.6917101]])
print (x*10) # Multiplies each element by 10

[[45.053314 17.296777 34.376245 55.10652 ]
 [54.627315  5.093587 40.067661 55.645993]
 [12.697628 82.485143 26.590556 56.917101]]


In [9]:
# E9
import pandas as pd # importing the library
log_data = pd.read_csv('C:\\Users\\PRANAV SAXENA\\Desktop\\Python\\basic_course-master\\Lecture_3\\data\\log_data_csv.csv') # reading the csv file
log_data.set_index('DEPTH', inplace= True) # set_index() sets the index to the specific value
log_data

ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04    BS  CALI  DRHO  DT  DTS  GR  \
DEPTH                                                                           
145.9        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.0        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.1        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.2        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.3        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
...          ...       ...       ...       ...   ...   ...   ...  ..  ...  ..   
3464.5       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.6       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.7       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.8       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.9       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   

        ...  PEF  RACEHM  RACELM  RD  RHOB  RM      ROP  RPCEHM  RPCELM  RT  
DEPTH   ...                                                                  
145.9   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.0   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.1   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.2   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.3   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
...     ...  ...     ...     ...  ..   ...  ..      ...     ...     ...  ..  
3464.5  ...  NaN     NaN     NaN NaN   NaN NaN  29.9836     NaN     NaN NaN  
3464.6  ...  NaN     NaN     NaN NaN   NaN NaN  29.9767     NaN     NaN NaN  
3464.7  ...  NaN     NaN     NaN NaN   NaN NaN  29.9699     NaN     NaN NaN  
3464.8  ...  NaN     NaN     NaN NaN   NaN NaN  29.9903     NaN     NaN NaN  
3464.9  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  

[33191 rows x 22 columns]

In [10]:
# E10 
bit_size = np.array(log_data['BS']) # Converts the column BS into an array
bit_size

array([36. , 36. , 36. , ...,  8.5,  8.5,  8.5])

In [11]:
# E11
log_data['BS'].value_counts() # Counts the frequency of bit sizes

17.5000    12469
26.0000    11289
12.2500     4827
8.5000      3800
36.0000      800
12.2283        2
8.5217         1
25.9508        1
17.4696        1
35.9421        1
Name: BS, dtype: int64

In [12]:
# E12
log_data['BS'].nunique() # Counts the number of unique values

10

In [13]:
# E13
log_data['GR'].describe() # Describes the statistics of GR, gamma ray column
percentile_25 = log_data['GR'].quantile(0.25) # Calculates 25 percentile GR
percentile_75 = log_data['GR'].quantile(0.75) # Calculates 75 percentile GR
min_gr = log_data['GR'].min() # Calculates minimum GR
median = log_data['GR'].median() # Calculates median GR
print ('Minimum GR = '+str(min_gr))
print ('Median GR = '+str(median))
print ('25 percentile gr = '+str(percentile_25))
print ('75 percentile gr = '+str(percentile_75))

Minimum GR = 0.1493
Median GR = 58.005700000000004
25 percentile gr = 29.481175
75 percentile gr = 79.2472


In [14]:
# E14
log_data['BS']=log_data['BS'].replace([36],40) # Replacing 36 BS with 40 BS
log_data['BS']

DEPTH
145.9     40.0
146.0     40.0
146.1     40.0
146.2     40.0
146.3     40.0
          ... 
3464.5     8.5
3464.6     8.5
3464.7     8.5
3464.8     8.5
3464.9     8.5
Name: BS, Length: 33191, dtype: float64

In [15]:
# E15
production_data = pd.read_csv('C:\\Users\\PRANAV SAXENA\\Desktop\\Python\\basic_course-master\\Lecture_3\\data\\prod_data.csv')
del production_data['Unnamed: 0']
production_data.dtypes

DATEPRD                      object
AVG_DOWNHOLE_PRESSURE       float64
AVG_DOWNHOLE_TEMPERATURE    float64
AVG_DP_TUBING               float64
AVG_ANNULUS_PRESS           float64
AVG_CHOKE_SIZE_P            float64
AVG_CHOKE_UOM                object
AVG_WHP_P                   float64
AVG_WHT_P                   float64
DP_CHOKE_SIZE               float64
BORE_OIL_VOL                float64
BORE_GAS_VOL                float64
BORE_WAT_VOL                float64
BORE_WI_VOL                 float64
FLOW_KIND                    object
WELL_TYPE                    object
dtype: object

In [16]:
# E16
production_data['DATEPRD']=pd.to_datetime(production_data['DATEPRD']) # pd.to_datetime() converts the type of column as date-time
production_data.dtypes

DATEPRD                     datetime64[ns]
AVG_DOWNHOLE_PRESSURE              float64
AVG_DOWNHOLE_TEMPERATURE           float64
AVG_DP_TUBING                      float64
AVG_ANNULUS_PRESS                  float64
AVG_CHOKE_SIZE_P                   float64
AVG_CHOKE_UOM                       object
AVG_WHP_P                          float64
AVG_WHT_P                          float64
DP_CHOKE_SIZE                      float64
BORE_OIL_VOL                       float64
BORE_GAS_VOL                       float64
BORE_WAT_VOL                       float64
BORE_WI_VOL                        float64
FLOW_KIND                           object
WELL_TYPE                           object
dtype: object

In [17]:
# E17
production_data['DATEPRD'] = production_data['DATEPRD'].dt.strftime('%Y') # dt.strftime() is used to change the format of date.
# Here %Y makes the format of the date only year.
production_groupby=production_data.groupby('DATEPRD').sum() # the data is sorted on the basis of year and values are added
production_groupby
# production_groupby([production_data.index]).sum()

AVG_DOWNHOLE_PRESSURE  AVG_DOWNHOLE_TEMPERATURE  AVG_DP_TUBING  \
DATEPRD                                                                   
2007                  0.000000                  0.000000       0.000000   
2008             126332.310680              53145.321325   86636.465440   
2009             171879.218917              74141.591116  121894.132257   
2010             160502.923169              66601.974941  132274.102660   
2011              83850.168072              34777.523747   83890.420230   
2012              78690.519824              34035.076791   77876.822481   
2013             127489.850406              51721.968030  114485.516138   
2014             317179.952517             140112.726769  268830.071114   
2015             349952.670812             151552.452285  299224.777084   
2016             216721.126936              86834.829308  198066.197563   

         AVG_ANNULUS_PRESS  AVG_CHOKE_SIZE_P     AVG_WHP_P      AVG_WHT_P  \
DATEPRD                                                                     
2007              0.000000          0.000000      0.000000       0.000000   
2008           4025.115398      19763.257827  39695.845240   36453.959314   
2009           5621.077441      33456.352462  51945.817217   55808.568903   
2010           8348.346807      41160.007435  37669.600702   61336.154932   
2011           6295.671376      43363.813540  31970.430852   54738.515777   
2012           6526.369311      51541.883105  23937.162317   54169.571480   
2013          15130.560085      61802.833284  36129.971488   69116.398131   
2014          27382.392622      78508.192935  78982.288089  103858.640858   
2015          22921.257036      84959.735169  79663.878891  109971.042472   
2016          20963.840959      77492.073819  35438.862473   73991.462309   

         DP_CHOKE_SIZE  BORE_OIL_VOL  BORE_GAS_VOL  BORE_WAT_VOL   BORE_WI_VOL  
DATEPRD                                                                         
2007          0.000000          0.00  0.000000e+00          0.00  0.000000e+00  
2008      27182.395652    1764375.15  2.570386e+08      23508.94  2.417770e+06  
2009      29335.704672    2684392.04  3.759820e+08     232103.74  4.392198e+06  
2010      14810.973585    1689902.55  2.439484e+08    1887594.78  4.569394e+06  
2011      12759.319522     847965.40  1.303202e+08    2190640.28  3.442446e+06  
2012       5627.735295     574206.33  9.020864e+07    2109601.63  2.975214e+06  
2013      12179.211410     558012.53  8.758778e+07    2576365.79  3.453761e+06  
2014      32737.373560     743107.49  1.117919e+08    2716070.92  3.825493e+06  
2015      30608.753230     861749.06  1.284238e+08    2009825.86  3.201627e+06  
2016      10264.390093     313370.06  5.006913e+07    1572866.41  2.052229e+06